// <auto-generated />
using System;
using FamilyFinance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyFinance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220173505_AddContributionBasisToSnapshotLines")]
    partial class AddContributionBasisToSnapshotLines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FamilyFinance.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInterest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            IsActive = true,
                            IsInterest = false,
                            Name = "BBVA - Capitale",
                            Owner = "Famiglia"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            IsActive = true,
                            IsInterest = true,
                            Name = "BBVA - Interessi",
                            Owner = "Famiglia"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            IsActive = true,
                            IsInterest = false,
                            Name = "ING - Capitale",
                            Owner = "Famiglia"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            IsActive = true,
                            IsInterest = true,
                            Name = "ING - Interessi",
                            Owner = "Famiglia"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            IsActive = true,
                            IsInterest = false,
                            Name = "UniCredit Riccardo",
                            Owner = "Riccardo"
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            IsActive = true,
                            IsInterest = false,
                            Name = "UniCredit Valentina",
                            Owner = "Valentina"
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            IsActive = true,
                            IsInterest = false,
                            Name = "FON.TE",
                            Owner = "Riccardo"
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            IsActive = true,
                            IsInterest = false,
                            Name = "Allianz",
                            Owner = "Famiglia"
                        });
                });

            modelBuilder.Entity("FamilyFinance.Models.Goal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deadline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Target")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("FamilyFinance.Models.InvestmentAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostBasis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PortfolioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("InvestmentAssets");
                });

            modelBuilder.Entity("FamilyFinance.Models.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeHorizonYears")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("FamilyFinance.Models.Receivable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("Receivables");
                });

            modelBuilder.Entity("FamilyFinance.Models.Snapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("FamilyFinance.Models.SnapshotLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ContributionBasis")
                        .HasColumnType("TEXT");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SnapshotId", "AccountId")
                        .IsUnique();

                    b.ToTable("SnapshotLines");
                });

            modelBuilder.Entity("FamilyFinance.Models.InvestmentAsset", b =>
                {
                    b.HasOne("FamilyFinance.Models.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId");

                    b.HasOne("FamilyFinance.Models.Snapshot", "Snapshot")
                        .WithMany("Investments")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FamilyFinance.Models.Receivable", b =>
                {
                    b.HasOne("FamilyFinance.Models.Snapshot", "Snapshot")
                        .WithMany("Receivables")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FamilyFinance.Models.SnapshotLine", b =>
                {
                    b.HasOne("FamilyFinance.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyFinance.Models.Snapshot", "Snapshot")
                        .WithMany("Lines")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FamilyFinance.Models.Snapshot", b =>
                {
                    b.Navigation("Investments");

                    b.Navigation("Lines");

                    b.Navigation("Receivables");
                });
#pragma warning restore 612, 618
        }
    }
}
